spring:
  datasource:
    username: admin
    password: HmIP6ecTZlQloUwioha4
    url: jdbc:mysql://to-get-db-1.cq3uctxl0ape.us-west-2.rds.amazonaws.com:3306/toget
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
